on: [push, pull_request]
name: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Install golangci-lint
      run: |
        GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.25.1
    - name: Run linters
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin   
        cd backend && ../pre-commit && cd -
        cd provisioning/add && ../../pre-commit && cd -
        cd provisioning/delete && ../../pre-commit && cd -
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Run build
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin   
        ./packager.sh